"""Load the DOC-01..DOC-07 snapshot exported from the TypeScript layer.

The snapshot is generated by ``scripts/exportKnowledge.ts`` and committed. This
module reads it, verifies it, and hands out typed accessors. It is the *only*
place in the Python service that knows what a fault or an anomaly is, so there
is exactly one copy of that knowledge in the process and it is a copy nobody
edited by hand.

Verification is not decoration. ``manifest.json`` carries a sha256 per file and
this loader checks every one, because the failure it prevents is the quiet
kind: a half-updated snapshot where the fault library moved and the anomaly
library did not, producing diagnoses that cite ids nothing else recognises.
A mismatch raises at load, before any request is served.

The loader is also where the *machine* knowledge stops and the ML service
begins. It answers "what does DOC-04 call this fault", never "is this fault
present" — that is the resolver's job, and keeping the two apart is what stops
the knowledge layer growing opinions.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable

from ..core.config import settings
from ..core.errors import KnowledgeError
from ..core.versions import KNOWLEDGE_SCHEMA_VERSION


@dataclass(frozen=True)
class FaultDefinition:
    """One row of the DOC-04 §11 fault master index."""

    fault_id: str
    name: str
    family: str
    primary_location: str
    applicable_states: str
    minimum_required_evidence: str
    rule_version: str


@dataclass(frozen=True)
class PatternDefinition:
    """One row of the DOC-04 §7 abnormal pattern library."""

    pattern_id: str
    name: str
    typical_evidence: str
    fault_candidate_direction: str


@dataclass(frozen=True)
class AnomalyDefinition:
    """One row of the DOC-07 Part A anomaly library."""

    anomaly_id: str
    name: str
    parameter: str
    primary_sensor: str
    output_state: str
    applicable_state: str
    primary_boundary: str
    healthy_behaviour: str
    formula_feature: str
    anomaly_decision: str
    persistence: str
    data_quality_gate: str
    context_gate: str


@dataclass(frozen=True)
class SignalDefinition:
    """One row of the DOC-02 §15 sensor and data-point master."""

    signal_id: str
    parameter: str
    location: str
    priority: str
    unit: str
    primary_use: str
    group: str
    canonical_tag: str
    canonical_location: str
    acquisition_class: str
    data_class: str
    supplied_by_machine: bool
    behaviour_if_missing: str


@dataclass(frozen=True)
class TagDefinition:
    """One installed instrument, joined to everything keyed on its tag.

    This is the row the feature engine actually reads. It carries the machine's
    own tag, the DOC-02 signal it supplies, the DOC-07 parameter family its
    anomalies are named from, its commissioning quality config and its
    cold-start baseline — so one lookup answers every question about a signal.
    """

    tag: str
    code: str
    label: str
    kind: str
    canonical_unit: str | None
    doc02_signal_id: str | None
    doc02_priority: str | None
    doc02_acquisition_class: str | None
    doc02_canonical_location: str | None
    doc07_parameter_family: str | None
    quality_config: dict[str, Any] | None
    template_baseline: dict[str, Any] | None

    @property
    def mandatory(self) -> bool:
        return self.doc02_priority == "MANDATORY"


@dataclass(frozen=True)
class OperatingStateDefinition:
    """One of the thirteen DOC-02 §4 states."""

    state_id: str
    name: str
    physical_meaning: str
    analytics_use: str
    baseline_learning: bool
    required_inputs: tuple[str, ...]
    reference_logic: str
    expected_behaviour: str
    implementation_note: str


@dataclass(frozen=True)
class FormulaDefinition:
    """One row of the DOC-03 §6 / §8 formula library."""

    formula_id: str
    name: str
    category: str
    logic: str
    inputs: str
    output: str
    purpose: str
    applicable_states: str
    guardrail: str
    version: str


class Knowledge:
    """The verified snapshot, with lookups over it."""

    def __init__(self, directory: Path) -> None:
        self.directory = directory
        self.manifest = self._read_manifest()
        self._verify()

        self.faults: tuple[FaultDefinition, ...] = tuple(
            FaultDefinition(
                fault_id=row["faultId"],
                name=row["name"],
                family=row["family"],
                primary_location=row["primaryLocation"],
                applicable_states=row["applicableStates"],
                minimum_required_evidence=row["minimumRequiredEvidence"],
                rule_version=row["ruleVersion"],
            )
            for row in self._read("faults.json")["faults"]
        )
        self.patterns: tuple[PatternDefinition, ...] = tuple(
            PatternDefinition(
                pattern_id=row["patternId"],
                name=row["name"],
                typical_evidence=row["typicalEvidence"],
                fault_candidate_direction=row["faultCandidateDirection"],
            )
            for row in self._read("faults.json")["patterns"]
        )
        self.anomalies: tuple[AnomalyDefinition, ...] = tuple(
            AnomalyDefinition(
                anomaly_id=row["anomalyId"],
                name=row["name"],
                parameter=row["parameter"],
                primary_sensor=row["primarySensor"],
                output_state=row["outputState"],
                applicable_state=row["applicableState"],
                primary_boundary=row["primaryBoundary"],
                healthy_behaviour=row["healthyBehaviour"],
                formula_feature=row["formulaFeature"],
                anomaly_decision=row["anomalyDecision"],
                persistence=row["persistence"],
                data_quality_gate=row["dataQualityGate"],
                context_gate=row["contextGate"],
            )
            for row in self._read("anomalies.json")["anomalies"]
        )
        self.signals: tuple[SignalDefinition, ...] = tuple(
            SignalDefinition(
                signal_id=row["signalId"],
                parameter=row["parameter"],
                location=row["location"],
                priority=row["priority"],
                unit=row["unit"],
                primary_use=row["primaryUse"],
                group=row["group"],
                canonical_tag=row["canonicalTag"],
                canonical_location=row["canonicalLocation"],
                acquisition_class=row["acquisitionClass"],
                data_class=row["dataClass"],
                supplied_by_machine=row["suppliedByMachine"],
                behaviour_if_missing=row["behaviourIfMissing"],
            )
            for row in self._read("signals.json")["signals"]
        )
        self.tags: tuple[TagDefinition, ...] = tuple(
            TagDefinition(
                tag=row["tag"],
                code=row["code"],
                label=row["label"],
                kind=row["kind"],
                canonical_unit=row["canonicalUnit"],
                doc02_signal_id=row["doc02SignalId"],
                doc02_priority=row["doc02Priority"],
                doc02_acquisition_class=row["doc02AcquisitionClass"],
                doc02_canonical_location=row["doc02CanonicalLocation"],
                doc07_parameter_family=row["doc07ParameterFamily"],
                quality_config=row["qualityConfig"],
                template_baseline=row["templateBaseline"],
            )
            for row in self._read("tags.json")["tags"]
        )
        self.states: tuple[OperatingStateDefinition, ...] = tuple(
            OperatingStateDefinition(
                state_id=row["stateId"],
                name=row["name"],
                physical_meaning=row["physicalMeaning"],
                analytics_use=row["analyticsUse"],
                baseline_learning=row["baselineLearning"],
                required_inputs=tuple(row["requiredInputs"]),
                reference_logic=row["referenceLogic"],
                expected_behaviour=row["expectedBehaviour"],
                implementation_note=row["implementationNote"],
            )
            for row in self._read("operating_states.json")["states"]
        )
        self.formulas: tuple[FormulaDefinition, ...] = tuple(
            FormulaDefinition(
                formula_id=row["formulaId"],
                name=row["name"],
                category=row["category"],
                logic=row["logic"],
                inputs=row["inputs"],
                output=row["output"],
                purpose=row["purpose"],
                applicable_states=row["applicableStates"],
                guardrail=row["guardrail"],
                version=row["version"],
            )
            for row in self._read("formulas.json")["formulas"]
        )
        self.enums: dict[str, Any] = self._read("enums.json")["enums"]
        self.commissioning: dict[str, Any] = self._read("commissioning.json")

        self._fault_by_id = {entry.fault_id: entry for entry in self.faults}
        self._pattern_by_id = {entry.pattern_id: entry for entry in self.patterns}
        self._anomaly_by_id = {entry.anomaly_id: entry for entry in self.anomalies}
        self._signal_by_id = {entry.signal_id: entry for entry in self.signals}
        self._state_by_id = {entry.state_id: entry for entry in self.states}
        self._formula_by_id = {entry.formula_id: entry for entry in self.formulas}
        # Several drawing points can share one analyser tag (the two gearbox
        # output vibration pads, for instance). First wins, deterministically,
        # because the registry is ordered and the duplicate rows agree on
        # everything the ML layer reads.
        self._tag_by_id: dict[str, TagDefinition] = {}
        for entry in self.tags:
            self._tag_by_id.setdefault(entry.tag, entry)

    # -- loading ----------------------------------------------------------

    def _read_manifest(self) -> dict[str, Any]:
        path = self.directory / "manifest.json"
        if not path.is_file():
            raise KnowledgeError(
                f"No knowledge snapshot at {self.directory}. "
                'Run "npm run export:knowledge" from the repository root.',
                detail={"directory": str(self.directory)},
            )
        manifest = json.loads(path.read_text(encoding="utf-8"))
        found = manifest.get("schemaVersion")
        if found != KNOWLEDGE_SCHEMA_VERSION:
            raise KnowledgeError(
                "Knowledge snapshot schema version mismatch. This service understands "
                f"{KNOWLEDGE_SCHEMA_VERSION}; the snapshot declares {found}.",
                detail={"expected": KNOWLEDGE_SCHEMA_VERSION, "found": found},
            )
        return manifest

    def _verify(self) -> None:
        """Check every file against the manifest hash before trusting any of it."""
        problems: list[str] = []
        for name, expected in self.manifest.get("files", {}).items():
            path = self.directory / name
            if not path.is_file():
                problems.append(f"{name} is missing")
                continue
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            if digest != expected:
                problems.append(f"{name} does not match its manifest hash")
        if problems:
            raise KnowledgeError(
                "The knowledge snapshot is inconsistent. Re-export it with "
                '"npm run export:knowledge".',
                detail={"problems": problems},
            )

    @lru_cache(maxsize=None)  # noqa: B019 - bound to one long-lived instance
    def _read(self, name: str) -> dict[str, Any]:
        return json.loads((self.directory / name).read_text(encoding="utf-8"))

    # -- lookups ----------------------------------------------------------

    def fault(self, fault_id: str) -> FaultDefinition | None:
        return self._fault_by_id.get(fault_id)

    def pattern(self, pattern_id: str) -> PatternDefinition | None:
        return self._pattern_by_id.get(pattern_id)

    def anomaly(self, anomaly_id: str) -> AnomalyDefinition | None:
        return self._anomaly_by_id.get(anomaly_id)

    def signal(self, signal_id: str) -> SignalDefinition | None:
        return self._signal_by_id.get(signal_id)

    def tag(self, tag: str) -> TagDefinition | None:
        return self._tag_by_id.get(tag)

    def state(self, state_id: str) -> OperatingStateDefinition | None:
        return self._state_by_id.get(state_id)

    def formula(self, formula_id: str) -> FormulaDefinition | None:
        return self._formula_by_id.get(formula_id)

    def faults_in_family(self, family: str) -> tuple[FaultDefinition, ...]:
        return tuple(entry for entry in self.faults if entry.family == family)

    def known_tags(self) -> tuple[str, ...]:
        return tuple(self._tag_by_id)

    def mandatory_tags(self) -> tuple[str, ...]:
        return tuple(entry.tag for entry in self._tag_by_id.values() if entry.mandatory)

    def baseline_learning_states(self) -> frozenset[str]:
        """States DOC-02 permits a steady baseline to be learned in.

        One state qualifies — ST-06 STEADY_PRODUCTION — and reading it from the
        snapshot rather than writing ``{"ST-06"}`` here means a document change
        propagates instead of being contradicted by a Python literal.
        """
        return frozenset(entry.state_id for entry in self.states if entry.baseline_learning)

    def anomaly_id_for(self, tag: str, direction: str) -> str | None:
        """The DOC-07 library id for a tag and a direction, or None.

        Mirrors ``anomalyIdFor`` in ``lib/knowledge/doc07/anomalies.ts``: match
        on parameter family plus direction, and return None rather than the
        nearest entry. An unlabelled anomaly is still a usable finding; a
        wrongly labelled one corrupts every ML label built on it.
        """
        entry = self.tag(tag)
        family = entry.doc07_parameter_family if entry else None
        if not family:
            return None
        suffix = {
            "HIGH_ANOMALY": "H",
            "LOW_ANOMALY": "L",
            "RISING_ABNORMAL": "ROC+",
            "FALLING_ABNORMAL": "ROC-",
            "OSCILLATING": "OSC",
        }.get(direction)
        if suffix is None:
            return None
        candidate = f"A-{family}-{suffix}"
        return candidate if candidate in self._anomaly_by_id else None

    def enum_values(self, name: str) -> tuple[str, ...]:
        """One enum from the snapshot, for asserting Python literals against."""
        values = self.enums.get(name)
        if not isinstance(values, list):
            raise KnowledgeError(f"enums.json has no list named {name!r}.")
        return tuple(str(value) for value in values)

    @property
    def field_calibrated(self) -> bool:
        """Whether the commissioning values were validated on a real machine."""
        return bool(self.commissioning.get("fieldCalibrated", False))

    @property
    def commissioning_notice(self) -> str:
        return str(self.commissioning.get("notice", ""))

    def describe(self) -> dict[str, Any]:
        """A summary for ``GET /health`` and the training run record."""
        return {
            "directory": str(self.directory),
            "schema_version": self.manifest.get("schemaVersion"),
            "documents": self.manifest.get("documents", {}),
            "counts": self.manifest.get("counts", {}),
            "field_calibrated": self.field_calibrated,
            "digest": self.digest(),
        }

    def digest(self) -> str:
        """One hash over the whole snapshot, stamped onto training runs."""
        joined = "".join(f"{name}:{digest}" for name, digest in sorted(self.manifest.get("files", {}).items()))
        return hashlib.sha256(joined.encode("utf-8")).hexdigest()[:16]


_KNOWLEDGE: Knowledge | None = None


def knowledge() -> Knowledge:
    """The process-wide snapshot, loaded and verified once."""
    global _KNOWLEDGE
    if _KNOWLEDGE is None:
        _KNOWLEDGE = Knowledge(settings().knowledge_dir)
    return _KNOWLEDGE


def reset_knowledge(replacement: Knowledge | None = None) -> None:
    """Replace the cached snapshot. Tests only."""
    global _KNOWLEDGE
    _KNOWLEDGE = replacement


def iter_fault_ids() -> Iterable[str]:
    return (entry.fault_id for entry in knowledge().faults)
